# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='apps',
            field=models.ManyToManyField(to='portal.Applications'),
        ),
    ]
