# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190316_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='fullname',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
