# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_applications_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='da',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Applications'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='apps',
            field=models.ManyToManyField(related_name='accessed_apps', to='portal.Applications'),
        ),
    ]
