# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190316_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='fullname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
