# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190316_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='da',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Applications'),
        ),
    ]
