# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-04 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20191104_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='da',
        ),
    ]
