# Generated by Django 4.2.6 on 2023-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='delay',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
