# Generated by Django 4.2.6 on 2023-10-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_events_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
