# Generated by Django 4.2.6 on 2023-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='remote_addr',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='remote_user',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='request_method',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
