# Generated by Django 4.2.6 on 2023-10-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_events_remote_addr_events_remote_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='remote_user',
        ),
    ]
