# Generated by Django 4.2.6 on 2023-11-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_events_remote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.applications'),
        ),
    ]
