# Generated by Django 2.1.5 on 2019-01-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipnames',
            name='ZipName',
            field=models.CharField(max_length=100),
        ),
    ]
