# Generated by Django 2.1.5 on 2019-01-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0003_auto_20190111_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='zipnames',
            old_name='ZipName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='ziprecord',
            name='zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip.ZipNames'),
        ),
    ]
