# Generated by Django 2.1.5 on 2019-01-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0005_ziprecord_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ziprecord',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ziprecord',
            name='order_template',
            field=models.IntegerField(default=0),
        ),
    ]
