# Generated by Django 2.1.5 on 2019-01-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0006_auto_20190111_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziprecord',
            name='order_id',
        ),
        migrations.AddField(
            model_name='ziprecord',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zip.ZipOrder'),
            preserve_default=False,
        ),
    ]
