# Generated by Django 2.1.5 on 2019-01-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0007_auto_20190111_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziprecord',
            name='order_template',
            field=models.BooleanField(default=False),
        ),
    ]
