# Generated by Django 2.1.5 on 2019-01-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0008_auto_20190111_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ziprecord',
            old_name='order_template',
            new_name='order_temp',
        ),
    ]
