# Generated by Django 2.1.5 on 2019-01-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0009_auto_20190111_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziprecord',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zip.ZipOrder'),
        ),
    ]
