# Generated by Django 2.1.5 on 2019-01-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zip', '0010_auto_20190111_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziprecord',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ziprecord',
            name='order_temp',
        ),
        migrations.AddField(
            model_name='ziporder',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ziporder',
            name='order_temp',
            field=models.BooleanField(default=False),
        ),
    ]
