# Generated by Django 2.1.5 on 2019-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0012_auto_20190111_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziprecord',
            name='comment',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
