# Generated by Django 2.1.5 on 2019-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0013_ziprecord_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziporder',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ziprecord',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
