# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0016_ziporder_order_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziporder',
            name='date_hidden',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
