# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0018_ziporder_date_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeZipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(blank=True, max_length=500)),
                ('amount', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zip.ZipOrder')),
            ],
        ),
    ]
