# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0019_freeziprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationaryNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StationeryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zip.ZipOrder')),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip.StationaryNames')),
            ],
        ),
    ]
