# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-10 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0021_zipidea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipidea',
            name='body',
            field=models.TextField(max_length=30000),
        ),
    ]
