# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-10 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0022_auto_20190310_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipidea',
            name='timestamp_create',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='zipidea',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
