# Generated by Django 4.2.6 on 2023-10-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0023_auto_20190310_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipusers',
            name='role',
            field=models.CharField(choices=[('teamlead', 'Руководитель группы'), ('controller', 'Контролер'), ('admin', 'Администратор')], max_length=100),
        ),
    ]
