# Generated by Django 4.2.6 on 2023-11-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='suppliesusers',
            name='role',
            field=models.CharField(choices=[('teamlead', 'Руководитель группы'), ('employee', 'Сотрудник группы'), ('controller', 'Контролёр'), ('admin', 'Администратор')], max_length=100),
        ),
        migrations.AddField(
            model_name='suppliesusers',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='supplies.suppliesgroup'),
            preserve_default=False,
        ),
    ]
