# Generated by Django 4.2.6 on 2023-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supplyname_supplyremain'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyname',
            name='type',
            field=models.CharField(choices=[('cartridge', 'Картридж'), ('cable', 'Кабели, переходники'), ('mouse', 'Мышь'), ('keyboard', 'Клавиатура')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
