# Generated by Django 4.2.6 on 2023-11-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0004_supplyname_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True, null=True)),
                ('itsm_id', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('placement', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='supplies.suppliesgroup')),
                ('supply', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='supplies.supplyremain')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
