# Generated by Django 4.2.6 on 2023-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_issuesupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesupply',
            name='device_model',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
