# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passes',
            name='passnumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
