# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_passes_passnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='passes',
            name='passtype',
            field=models.CharField(choices=[(b'afl', b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xbf\xd1\x83\xd1\x81\xd0\xba \xd0\x90\xd0\xa4\xd0\x9b'), (b'mash', b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xbf\xd1\x83\xd1\x81\xd0\xba \xd0\x9c\xd0\x90\xd0\xa8')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
