# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_passes_passtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='passes',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
