# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_passes_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassesEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
